
name: Docker-Images-Build

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-java@v1
       with:
         java-version: 11
     - uses: docker/setup-buildx-action@v1
     - uses: actions/setup-node@v1
       with:
         node-version: 12.x
         
     - name: Build sote-frontend
       run: |
          echo '=====开始安装sote-frontend依赖====='
          npm install
          npm run build:prod
          
    # 构建镜像，指定镜像名
     - name: Build Vue Docker Images
       run: |
          echo '=====开始构建镜像====='
          echo '=====开始构建 sote-frontend====='
          
          docker build -t registry.cn-hangzhou.aliyuncs.com/sote/sote-frontend
          
     # 登录到 阿里云镜像服务，使用 GitHub secrets 传入账号密码，密码被加密存储在 GitHub 服务器
     - name: Login to Aliyun
       uses: docker/login-action@v1
       with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USER_NAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          
          
     - name: push Images to DockerHub
       run: |
          docker images
          echo '======= 开始上传镜像 ======='
          
          echo '======= 开始上传sote-frontend ======='
          docker push registry.cn-hangzhou.aliyuncs.com/sote/sote-frontend
          
          echo '=====镜像上传结束====='
          
#      - name: Update New Docker Image And Restart Server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SERVER_IP }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          password: ${{ secrets.SERVER_PASSWORD }}
#          port: 22
#          script: |
#            cd /root/sote-backend
#            ./update.sh
